### ISSUE TITLE
Prepare for Monthly Closing

### ISSUE THREAD

**Issue by sorawitmon** [anisonglopez/new_pr#5]
เรียงลำดับจาก มากไปหาน้อย ตามรูป
![prepare_monthly](https://user-images.githubusercontent.com/42995876/50053737-bb2e9a00-016c-11e9-8e48-80338363261a.png)

**Comment by anisonglopez** [comment]
```
<script>
 $(document).ready(function() {
        $('#dataTables-example').DataTable({
            responsive: true,
            "order": [[ 0, "desc" ]]
        });
    });
</script>
```

**Comment by sorawitmon** [comment]
ยังไ่ม่ผ่าน ที่ถูกต้อง จะต้องแสดงดังนี้
201812  2
201812  1
201811  2
201811  1
