### ISSUE TITLE
Create prepare for monthly Closing 

### ISSUE THREAD

**Issue by sorawitmon** [anisonglopez/new_pr#6]
กรณีเลือกรายวัน จะต้องมี Company Holiday  ให้กรอกด้วย
![prepare_monthly2](https://user-images.githubusercontent.com/42995876/50053781-5c1d5500-016d-11e9-9770-33587472b5f0.png)

**Comment by anisonglopez** [comment]
สร้าง Field Holiday ขึ้นมาใหม่

**Comment by anisonglopez** [comment]
Holiday int (10)

**Comment by anisonglopez** [comment]
เครื่อง Dev สร้าง Field นี้แล้ว

**Comment by sorawitmon** [comment]
การแสดง company holiday ยังไม่ผ่าน ทำสลับกัน ตอนนี้เลือกรายเดือน จึงจะมีให้กรอก
