### ISSUE TITLE
Change Overtime รูป1

### ISSUE THREAD

**Issue by sorawitmon** [anisonglopez/new_pr#8]
![overtime1](https://user-images.githubusercontent.com/42995876/50054070-8fadae80-0170-11e9-9464-35a973a1367e.png)
![overtime2](https://user-images.githubusercontent.com/42995876/50054096-0054cb00-0171-11e9-9f93-edfe10de787b.png)

**Comment by anisonglopez** [comment]
เปลี่ยน Field Employee Name เป็น พนักงาน แล้ว
